spring:
  datasource:
#    url: jdbc:mysql://121.40.113.226:3306/mem?characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/mem?characterEncoding=utf-8&serverTimezone=UTC
    username: memuser
    password: Xny3epGpZJEXj
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7778


#mybatis-plus:
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mica:
  xss:
    mode: clear
